openapi: 3.0.0
info:
  title: word-guessing-game API
  version: '1.0'
  description: |-
    A clone of the game wordle but with micro frontend and webcomponents.

    The following API endpoints are documented here:
    - **GET:** /getWord

    The following database models are also documented here:

    - Word
  contact:
    url: 'https://github.com/reyes-edwin/word-guessing-game'
servers:
  - url: 'https://word-guessing-game-seven.vercel.app/api'
paths:
  /getWord:
    get:
      summary: getWord
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    word: string
                    date: date
                properties:
                  word:
                    type: string
                    maxLength: 5
                  date:
                    type: string
                    format: date
                    example: '2022-04-14'
                required:
                  - word
                  - date
              examples:
                example-1:
                  value:
                    word: string
                    date: '2019-08-24'
      operationId: getWord
      description: A JSON response containing the word of the day for either the current date or a randomized date
      parameters:
        - schema:
            type: string
            example: '2022-05-12'
          in: query
          name: myDay
          description: Input of either the current date to retrieve the word of the day or the value `random` to retrieve a randomized word of the day
          required: true
          components:
  schemas:
    Word:
      title: Word
      type: object
      description: ''
      x-examples:
        Arise:
          word: Arise
          date: '1997-10-31'
      properties:
        word:
          type: string
        date:
          type: string
          format: date
          example: '1997-10-31'
      required:
        - word